export const sampleProperties = [
  {
    _id: 'sample-1',
    title: 'Modern Luxury Villa',
    description: 'Stunning villa with panoramic views, private pool, and smart home features in a gated community.',
    location: 'Beverly Hills, CA',
    address: '123 Sunset Boulevard',
    price: 4500,
    type: 'villa',
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    amenities: ['Parking', 'Swimming Pool', 'Gym', 'Security', 'Garden'],
    status: 'approved',
    contactNumber: '+1 555-0101',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    ],
    owner: { name: 'John Smith', email: 'john@example.com', phone: '+1 555-0101' },
  },
  {
    _id: 'sample-2',
    title: 'Downtown Apartment',
    description: 'Contemporary apartment in the heart of the city with floor-to-ceiling windows and rooftop access.',
    location: 'Manhattan, NY',
    address: '456 Park Avenue',
    price: 2800,
    type: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    amenities: ['WiFi', 'Elevator', 'Gym', 'Security'],
    status: 'approved',
    contactNumber: '+1 555-0102',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    owner: { name: 'Sarah Johnson', email: 'sarah@example.com', phone: '+1 555-0102' },
  },
  {
    _id: 'sample-3',
    title: 'Cozy Family House',
    description: 'Beautiful family home with spacious backyard, updated kitchen, and excellent school district.',
    location: 'Austin, TX',
    address: '789 Oak Street',
    price: 2200,
    type: 'house',
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    amenities: ['Parking', 'Garden', 'Pet Friendly', 'Air Conditioning'],
    status: 'approved',
    contactNumber: '+1 555-0103',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    owner: { name: 'Mike Davis', email: 'mike@example.com', phone: '+1 555-0103' },
  },
  {
    _id: 'sample-4',
    title: 'Seaside Villa Retreat',
    description: 'Exclusive beachfront villa with private access, infinity pool, and breathtaking ocean views.',
    location: 'Miami, FL',
    address: '321 Ocean Drive',
    price: 5500,
    type: 'villa',
    bedrooms: 5,
    bathrooms: 4,
    area: 4000,
    amenities: ['Swimming Pool', 'Parking', 'WiFi', 'Security', 'Furnished'],
    status: 'approved',
    contactNumber: '+1 555-0104',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1605276374101-e4f076223691?w=800',
    ],
    owner: { name: 'Emily Wilson', email: 'emily@example.com', phone: '+1 555-0104' },
  },
  {
    _id: 'sample-5',
    title: 'Urban Loft Apartment',
    description: 'Industrial-chic loft with exposed brick, high ceilings, and walking distance to cafes and transit.',
    location: 'Chicago, IL',
    address: '654 W Lake St',
    price: 1900,
    type: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    area: 900,
    amenities: ['WiFi', 'Elevator', 'Air Conditioning'],
    status: 'approved',
    contactNumber: '+1 555-0105',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    owner: { name: 'Alex Brown', email: 'alex@example.com', phone: '+1 555-0105' },
  },
  {
    _id: 'sample-6',
    title: 'Suburban Dream Home',
    description: 'Spacious suburban house with modern finishes, two-car garage, and landscaped front yard.',
    location: 'Seattle, WA',
    address: '987 Pine Road',
    price: 3100,
    type: 'house',
    bedrooms: 4,
    bathrooms: 3,
    area: 2400,
    amenities: ['Parking', 'Garden', 'WiFi', 'Air Conditioning'],
    status: 'approved',
    contactNumber: '+1 555-0106',
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
    ],
    owner: { name: 'Lisa Chen', email: 'lisa@example.com', phone: '+1 555-0106' },
  },
];

export const testimonials = [
  { id: 1, name: 'Robert Anderson', role: 'Property Owner', text: 'Listing my properties was effortless. The admin approval process is smooth and professional.', rating: 5, avatar: 'https://i.pravatar.cc/150?img=12' },
  { id: 2, name: 'Maria Garcia', role: 'Home Seeker', text: 'Found my dream apartment within days. The search filters and property details are excellent.', rating: 5, avatar: 'https://i.pravatar.cc/150?img=45' },
  { id: 3, name: 'David Kim', role: 'Property Owner', text: 'The owner dashboard gives me complete control over my listings. Highly recommended platform.', rating: 5, avatar: 'https://i.pravatar.cc/150?img=33' },
];

export const stats = [
  { label: 'Properties Listed', value: '2,500+' },
  { label: 'Happy Owners', value: '1,200+' },
  { label: 'Cities Covered', value: '50+' },
  { label: 'Years Experience', value: '10+' },
];

export const whyChooseUs = [
  { icon: 'shield', title: 'Verified Listings', desc: 'Every property is reviewed and approved by our admin team for quality assurance.' },
  { icon: 'search', title: 'Smart Search', desc: 'Advanced filters help you find the perfect property by location, price, and type.' },
  { icon: 'support', title: '24/7 Support', desc: 'Our dedicated team is always ready to assist owners and visitors.' },
  { icon: 'chart', title: 'Analytics Dashboard', desc: 'Owners get real-time insights on property status and performance.' },
];
